use std::{sync::Arc, collections::{HashMap}};

use async_recursion::async_recursion;
use merkle_light::merkle::MerkleTree;
use types::{Replica, hash_cc::{ProtMsg, WrapperMsg, CTRBCMsg}, appxcon::{verify_merkle_proof, reconstruct_and_return, HashingAlg}};

use crate::node::{Context, process_batchwssready};
use crypto::hash::{Hash};

#[async_recursion]
pub async fn process_batch_wssecho(cx: &mut Context,ctrbc:CTRBCMsg,master_root:Hash ,echo_sender:Replica){
    let vss_state = &mut cx.batchvss_state;
    let sec_origin = ctrbc.origin;
    let mut msgs_to_be_sent:Vec<ProtMsg> = Vec::new();
    // Highly unlikely that the node will get an echo before rbc_init message
    log::info!("Received ECHO message {:?} for secret from {}",ctrbc.clone(),echo_sender);
    // If RBC already terminated, do not consider this RBC
    if vss_state.terminated_secrets.contains(&sec_origin){
        log::info!("Terminated secretsharing of instance {} already, skipping this echo",sec_origin);
        return;
    }
    match vss_state.node_secrets.get(&sec_origin){
        None => {
            let mut echoset = HashMap::default();
            echoset.insert(echo_sender,(ctrbc.shard,ctrbc.mp));
            vss_state.echos.insert(ctrbc.origin, echoset);
            return;
        }
        Some(_x) =>{}
    }
    let mp = vss_state.node_secrets.get(&sec_origin).unwrap().master_root;
    if mp != master_root{
        log::error!("Merkle root of WSS Init from {} did not match Merkle root of ECHO from {}",sec_origin,cx.myid);
        return;
    }
    let shard = ctrbc.shard.clone();
    let mp = ctrbc.mp.clone();
    let rbc_origin = ctrbc.origin.clone();
    if !verify_merkle_proof(&mp, &shard){
        log::error!("Failed to evaluate merkle proof for ECHO received from node {} for RBC {}",echo_sender,rbc_origin);
        return;
    }
    match vss_state.echos.get_mut(&sec_origin) {
        None => {
            let mut echoset = HashMap::default();
            echoset.insert(echo_sender,(shard.clone(),mp.clone()));
            vss_state.echos.insert(rbc_origin, echoset);
        },
        Some(x) => {
            x.insert(echo_sender,(shard.clone(),mp.clone()));
        }
    }
    let echos = vss_state.echos.get_mut(&sec_origin).unwrap();
    // 2. Check if echos reached the threshold, init already received, and round number is matching
    log::debug!("WSS ECHO check: echos.len {}, contains key: {}"
    ,echos.len(),vss_state.node_secrets.contains_key(&sec_origin));
    if echos.len() == cx.num_nodes-cx.num_faults && 
        vss_state.node_secrets.contains_key(&sec_origin){
        // Broadcast readys, otherwise, just wait longer
        // Cachin-Tessaro RBC implies verification needed
        // Send your own shard in the echo phase to every other node. 
        let merkle_root = vss_state.node_secrets.get(&sec_origin).unwrap().master_root.clone();
        let mut echo_map = HashMap::default();

        for (rep,(shard,_mp)) in echos.clone().into_iter(){
            echo_map.insert(rep, shard);
        }
        let res = 
            reconstruct_and_return(&echo_map, cx.num_nodes.clone(), cx.num_faults.clone());
        match res {
            Err(error)=> log::error!("Shard reconstruction failed because of the following reason {:?}",error),
            Ok(vec_x)=> {
                // Further verify the merkle root generated by these hashes
                let mut vec_xx = vec_x;
                vec_xx.truncate(cx.num_nodes*32);
                log::info!("Vec_x: {:?} {}",vec_xx.clone(),vec_xx.len());
                let split_vec:Vec<Hash> = 
                    vec_xx.chunks(32).into_iter()
                    .map(|x| {
                        x.try_into().unwrap()
                    })
                    .collect();
                let merkle_tree_master:MerkleTree<Hash,HashingAlg> = MerkleTree::from_iter(split_vec.clone().into_iter());
                if merkle_tree_master.root() == merkle_root{
                    let shard = echos.get(&cx.myid).unwrap();
                    let ctrbc = CTRBCMsg::new(shard.0.clone(), shard.1.clone(), 0, rbc_origin);
                    msgs_to_be_sent.push(ProtMsg::BatchWSSReady(ctrbc,merkle_root, cx.myid))
                }
                else {
                    log::error!("Reconstructing root hash polynomial failed, with params {:?} {:?} {:?}", split_vec.clone(),merkle_tree_master.root(),merkle_root);
                    return;
                }
            }
        }
    }
    // Inserting send message block here to not borrow cx as mutable again
    for prot_msg in msgs_to_be_sent.into_iter(){
        let sec_key_map = cx.sec_key_map.clone();
        for (replica,sec_key) in sec_key_map.into_iter() {
            if replica != cx.myid{
                let wrapper_msg = WrapperMsg::new(prot_msg.clone() ,cx.myid, &sec_key.as_slice());
                let sent_msg = Arc::new(wrapper_msg);
                cx.c_send(replica, sent_msg).await;
            }
            else {
                match prot_msg.clone() {
                    ProtMsg::BatchWSSReady(ctr,mr, sender)
                    => {process_batchwssready(cx,ctr.clone(),mr,sender).await;}
                    _ =>{}
                }
            }
        }
        log::info!("Broadcasted message {:?}",prot_msg.clone());
    }
}